services:
  hub:
    container_name: f1_hub
    build:
      context: ./hub
      dockerfile: Dockerfile.dev
    ports:
      - "9010:5000"
    volumes:
      - ./hub:/app
    env_file:
      - ./envs/.env.hub
    depends_on:
      - postgres
    networks:
      - f1_network

  postgres:
    image: postgres:14
    container_name: f1_postgres
    hostname: f1_postgres
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/.env.postgres
    networks:
      - f1_network
    ports:
      - "9040:5432"
    restart: "always"

  redis:
    image: redis:6.2-alpine
    container_name: f1_redis
    hostname: f1_redis
    ports:
      - "9050:6379"
    networks:
      - f1_network
    restart: "always"

networks:
  f1_network:
    name: f1_network
    driver: bridge